export const areaLinks = [
	{
		id: "next",
		title: "Next to work on",
	},
	{
		id: "logbook",
		title: "Logbook",
	},
	{
		id: "home",
		title: "Home",
	},
	{
		id: "work",
		title: "Work",
	},
	{
		id: "education",
		title: "Education",
	},
	{
		id: "shopping",
		title: "Shopping",
	},
	{
		id: "entertainment",
		title: "Entertainment",
	},
	{
		id: "fitness",
		title: "Fitness",
	},
]

export const goalLinks = [
	{
		id: "website",
		title: "Build new website",
		due_date: 4
	},
	{
		id: "prepare",
		title: "Prepare team offsite",
		due_date: 62
	},
	{
		id: "interviews",
		title: "Be a better interviewer",
		due_date: null
	},
	{
		id: "promoted",
		title: "Get promoted",
		due_date: null
	},
]

export const priorityLinks = [
	{
		id: "must",
		title: "Must",
	},
	{
		id: "should",
		title: "Should",
	},
	{
		id: "want",
		title: "Want",
	},
]

export const initTasks = [
    {
      "id": 1,
      "area_id": "Software Dev",
      "goal_id": null,
      "status": "now",
      "previous_status": "later",
	  "checked": false,
      "estimate": 10,
      "priority": 0,
    },
    {
      "id": 2,
      "area_id": "Software Dev",
      "goal_id": null,
      "status": "later",
      "previous_status": null,
	  "checked": false,
      "estimate": 120,
      "priority": 0,
    },
    {
      "id": 3,
      "area_id": "Software Dev",
      "goal_id": null,
      "status": "later",
      "previous_status": null,
	  "checked": false,
      "estimate": 120,
      "priority": 0,
    },
    {
      "id": 4,
      "area_id": "Software Dev",
      "goal_id": null,
      "status": "later",
      "previous_status": null,
	  "checked": false,
      "estimate": 120,
      "priority": 0,
    },
    {
      "id": 5,
      "area_id": "Software Dev",
      "goal_id": null,
      "status": "later",
      "previous_status": null,
	  "checked": false,
      "estimate": 120,
      "priority": 0,
    },
    {
      "id": 6,
      "area_id": "Software Dev",
      "goal_id": null,
      "status": "later",
      "previous_status": null,
	  "checked": false,
      "estimate": 120,
      "priority": 0,
    },
    {
      "id": 7,
      "area_id": "Software Dev",
      "goal_id": null,
      "status": "later",
      "previous_status": null,
	  "checked": false,
      "estimate": 120,
      "priority": 0,
    },
    {
      "id": 8,
      "area_id": "Software Dev",
      "goal_id": null,
      "status": "later",
      "previous_status": null,
	  "checked": false,
      "estimate": 120,
      "priority": 0,
    },
    {
      "id": 9,
      "area_id": "Software Dev",
      "goal_id": null,
      "status": "later",
      "previous_status": null,
	  "checked": false,
      "estimate": 120,
      "priority": 0,
    },
    {
      "id": 10,
      "area_id": "Software Dev",
      "goal_id": null,
      "status": "later",
      "previous_status": null,
	  "checked": false,
      "estimate": 120,
      "priority": 0,
    },
  ]

export const navLinks = [
    {
        id: "dashboard",
        title: "Dashboard",
    },
    {
        id: "today",
        title: "Today",
    },
    {
        id: "stats",
        title: "Stats",
    },
    {
        id: "feed",
        title: "Feed",
    },
    {
        id: "profile",
        title: "Profile",
    }
  ];

export const habits = [{
	habit: 'Drink water',
	description: 'Stay hydrated & flush out toxins',
	category: 'Healthy body',
	special: 'Become a hydration sensation! Drinking enough water increases your energy levels and your brain function. Staying hydrated is key to your health.',
	icon: 'Droplet',
	color: 'Blue',
	unit: 'glass',
	units: 'glasses',
},
{
	habit: 'Eat a healthy meal',
	description: 'Energize with high quality nutrients your body craves',
	category: 'Healthy body',
	special: 'Good nutrition is crucial for a healthy lifestyle. It can help you reach and meaintain a healthy weight, reduce your risk of chronic diseases and improve your overall health.',
	icon: 'Cutlery',
	color: 'Purple',
	unit: 'plate',
	units: 'plates',
},
{
	habit: 'Eat fruits and veggies',
	description: 'Natural source of carbohydrates, essential nutrients and fiber',
	category: 'Healthy body',
	icon: 'Apple',
	color: 'Green',
	unit: 'time',
	units: 'times',
},
{
	habit: 'Take vitamins',
	description: 'Give your immune system a boost',
	category: 'Healthy body',
	icon: 'Pill',
	color: 'Yellow',
	unit: 'time',
	units: 'times',
},
{
	habit: 'Cook a balanced meal',
	description: 'Cook your favorite recipe',
	category: 'Healthy body',
	icon: 'Fire',
	color: 'Orange',
	unit: 'time',
	units: 'times',
},
{
	habit: 'Fast',
	description: 'Cleanse the body and mind',
	category: 'Healthy body',
	icon: 'Ban',
	color: 'Red',
	unit: 'time',
	units: 'times',
},
{
	habit: 'Limit processed sugar',
	description: 'Choose natural sugars like fruits and veggies',
	category: 'Healthy body',
	icon: 'SugarBan',
	color: 'White',
	unit: 'time',
	units: 'times',
},
{
	habit: 'Limit fried food',
	description: 'Choose healthier baked options instead',
	category: 'Healthy body',
	icon: 'FryBan',
	color: 'Yellow',
	unit: 'time',
	units: 'times',
},
{
	habit: 'Limit caffeine',
	description: 'Choose lower caffeine options like tea instead',
	category: 'Healthy body',
	icon: 'CupOfTea',
	color: 'Brown',
	unit: 'time',
	units: 'times',
},
{
	habit: 'Hit the gym',
	description: 'Exercise fills your body with endorphins',
	category: 'Staying fit',
	icon: 'Dumbbell',
	color: 'Red',
	unit: 'time',
	units: 'times',
},
{
	habit: 'Exercise',
	description: 'Get that workout in',
	category: 'Staying fit',
	icon: 'SitUp',
	color: 'Orange',
	unit: 'time',
	units: 'times',
},
{
	habit: 'Go for a walk',
	description: 'Walking strengthens your bones and improves your mood',
	category: 'Staying fit',
	icon: 'Tree',
	color: 'Green',
	unit: 'time',
	units: 'times',
},
{
	habit: 'Go for a run',
	description: 'Improve cardiovascular fitness and sweat out stress in no time',
	category: 'Staying fit',
	icon: 'Runner',
	color: 'Blue',
	unit: 'time',
	units: 'times',
},
{
	habit: 'Go for a ride',
	description: 'Pedal to the pavement',
	category: 'Staying fit',
	icon: 'Bicycle',
	color: 'Red',
	unit: 'time',
	units: 'times',
},
{
	habit: 'Go for a swim',
	description: 'Non-impact cardiovascular fitness is a great option',
	category: 'Staying fit',
	icon: 'Swimmer',
	color: 'Blue',
	unit: 'time',
	units: 'times',
},
{
	habit: 'Yoga session',
	description: 'Align with your core self',
	category: 'Staying fit',
	icon: 'WarriorOne',
	color: 'Green',
	unit: 'time',
	units: 'times',
},
{
	habit: 'Do some stretching',
	description: 'Flexibility is key for healthy movement',
	category: 'Staying fit',
	icon: 'Stretch',
	color: 'Orange',
	unit: 'time',
	units: 'times',
},
{
	habit: 'Check posture',
	description: 'Are you slouching?',
	category: 'Staying fit',
	icon: 'StandStraight',
	color: 'Yellow',
	unit: 'time',
	units: 'times',
},
{
	habit: 'Spend time with family',
	description: 'Stay connected',
	category: 'Loved ones',
	icon: 'ManAndWoman',
	color: 'Orange',
	unit: 'time',
	units: 'times',
},
{
	habit: 'Meet with a friend',
	description: 'Make new memories',
	category: 'Loved ones',
	icon: 'TextBubble',
	color: 'Green',
	unit: 'time',
	units: 'times',
},
{
	habit: 'Call parents',
	description: 'They love you',
	category: 'Loved ones',
	icon: 'Phone',
	color: 'Purple',
	unit: 'time',
	units: 'times',
},
{
	habit: 'Make a gift',
	description: 'Make someone smile today',
	category: 'Loved ones',
	icon: 'Present',
	color: 'Yellow',
	unit: 'time',
	units: 'times',
},
{
	habit: 'Hug and kiss',
	description: 'Showing love and affection is easy',
	category: 'Loved ones',
	icon: 'Heart',
	color: 'Red',
	unit: 'time',
	units: 'times',
},
{
	habit: 'Cuddle',
	description: 'Embrace your tender side',
	category: 'Loved ones',
	icon: 'ManAndWoman',
	color: 'Blue',
	unit: 'time',
	units: 'times',
},
{
	habit: 'Pay bills',
	description: 'Out of sight, out of mind',
	category: 'Personal finance',
	icon: 'CreditCard',
	color: 'Purple',
	unit: 'time',
	units: 'times',
},
{
	habit: 'Track my expenses',
	description: 'Bring awareness to spending patterns',
	category: 'Personal finance',
	icon: 'Chart',
	color: 'Yellow',
	unit: 'time',
	units: 'times',
},
{
	habit: 'Save at least 10%',
	description: 'Build yourself a safety net',
	category: 'Personal finance',
	icon: 'Coins',
	color: 'Green',
	unit: 'time',
	units: 'times',
},
{
	habit: 'Plan my spending',
	description: 'No more impulsive purchases',
	category: 'Personal finance',
	icon: 'Papers',
	color: 'Orange',
	unit: 'time',
	units: 'times',
},
{
	habit: 'Donate',
	description: 'Giving is a way of showing gratitude',
	category: 'Personal finance',
	icon: 'Envelope',
	color: 'Blue',
	unit: 'time',
	units: 'times',
},
{
	habit: 'Limit eating out',
	description: 'Cook something at home',
	category: 'Personal finance',
	icon: 'Cutlery',
	color: 'Red',
	unit: 'time',
	units: 'times',
},
{
	habit: 'Create shopping list',
	description: 'Plan for saving time and money',
	category: 'Personal finance',
	icon: 'Basket',
	color: 'Yellow',
	unit: 'time',
	units: 'times',
},
{
	habit: 'Take out the trash',
	description: 'Keep your home clean',
	category: 'Houehold chores',
	icon: 'TrashBin',
	color: 'Green',
	unit: 'time',
	units: 'times',
},
{
	habit: 'Tidy the house',
	description: 'Keep it sparkling',
	category: 'Houehold chores',
	icon: 'Duster',
	color: 'Orange',
	unit: 'time',
	units: 'times',
},
{
	habit: 'Do the laundry',
	description: 'Separate your lights and darks',
	category: 'Houehold chores',
	icon: 'laundry',
	color: 'Blue',
	unit: 'time',
	units: 'times',
},
{
	habit: 'Vacuum',
	description: 'Clear out the dust and dirt',
	category: 'Houehold chores',
	icon: 'Vacuum',
	color: 'Red',
	unit: 'time',
	units: 'times',
},
{
	habit: 'Water the plants',
	description: 'Keep plants alive and well',
	category: 'Houehold chores',
	icon: 'Plant',
	color: 'Blue',
	unit: 'time',
	units: 'times',
},
{
	habit: 'Work in the garden',
	description: 'Caring for plants can lift your spirits',
	category: 'Houehold chores',
	icon: 'Plant',
	color: 'Yellow',
	unit: 'time',
	units: 'times',
}]