import { Inter, Roboto_Mono } from 'next/font/google'
import { Nav, Provider } from '../components';
import '/styles/globals.css'

const inter = Inter({ subsets: ['latin'] })

const roboto = Roboto_Mono({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="author" content="Michael Toce" />
        <meta name="description" content="My First Full-Stack Web Application created with Next JS, React & TailwindCSS. Habit Hacks is a habit tracking tool for users." />
      </head>
      <body className={roboto.className}>
        <Provider>
          <main className='flex flex-row w-full'>
            <Nav />
            {children}
          </main>
        </Provider>
      </body>
    </html>
  )
}

export default RootLayout