import { Inter, Roboto_Mono } from 'next/font/google'
import { Dashboard, Feed, Footer, Habits, Nav, Profile, Provider } from '../components';
import '/styles/globals.css'

const inter = Inter({ subsets: ['latin'] })

const roboto = Roboto_Mono({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Provider>
          <main>
            <Nav />
            {children}
          </main>
        </Provider>
      </body>
    </html>
  )
}

export default RootLayout